apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: performance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/CSXGIT/k8s-manifests.git
    targetRevision: master
    path: environments/qa-cluster/performance
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true