apiVersion: v1
kind: Service
metadata:
  name: sample-site-2
  labels:
    app.kubernetes.io/name: sample-site-2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: sample-site-2