apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: performance
commonLabels:
  env: performance
resources:
- namespace.yaml
# - ../../../applications/sample-site


images:
- name: victorcuascut/sample-site
  newName: victorcuascut/sample-site
  newTag: "v2.0"