apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
commonLabels:
  env: production
resources:
- namespace.yaml
# - ../../../applications/sample-site

# images:
# - name: victorcuascut/sample-site
#   newName: victorcuascut/sample-site
#   newTag: "v1.0"